language: minimal
dist: xenial

services:
  - docker

before_install:
  - docker pull pylipp/sdd

script:
  - ./test/run.sh --style
  - ./test/run.sh

cache:
    directories:
        - $HOME/.cache/pre-commit
