language: minimal
dist: xenial

addons:
  apt:
    packages:
    - python3-venv

services:
  - docker

before_install:
  - docker pull pylipp/sdd
  - ./test/setup/venv

script:
  - ./test/run.sh --style
  - ./test/run.sh

cache:
    directories:
        - $HOME/.cache/pre-commit
        - $HOME/.cache/pip
